/** @file
 *	@brief MAVLink comm protocol generated from mace_mission.xml
 *	@see http://mavlink.org
 */

#pragma once

#include <array>
#include <cstdint>
#include <sstream>

#ifndef MAVLINK_STX
#define MAVLINK_STX 253
#endif

#include "../message.hpp"

namespace mavlink {
namespace mace_mission {

/**
 * Array of msg_entry needed for @p mavlink_parse_char() (trought @p mavlink_get_msg_entry())
 */
constexpr std::array<mavlink_msg_entry_t, 4> MESSAGE_ENTRIES {{ {12500, 132, 5, 5, 0, 0, 0}, {12501, 219, 1, 1, 1, 0, 0}, {12502, 21, 2, 2, 1, 0, 0}, {12503, 12, 18, 18, 0, 0, 0} }};

//! MAVLINK VERSION
constexpr auto MAVLINK_VERSION = 3;


// ENUM DEFINITIONS


/** @brief Type of mission items being requested/sent in mission protocol. */
enum class MAV_MISSION_STATE
{
    CURRENT=0, /* Items are mission commands for main auto mission and are received via the autopilot and aircraft module. | */
    ONBOARD=1, /* Items are mission ready and have been acknowledged by the aircraft module for processing. | */
    PROPOSED=2, /* Items are mission ready but have been generated by a module not related to the aircraft and need to be pushed towards the appropriate aircraft module. | */
    RECEIVED=3, /* Items have been distributed and received by the appropriate MACE instance connected to the associated module. They however have yet to be marked as current or onboard. Often this state is reflected via communication between external link modules. | */
    OUTDATED=4, /* Items were once relevant to the system have been since replaced with newer current missions. | */
};

//! MAV_MISSION_STATE ENUM_END
constexpr auto MAV_MISSION_STATE_ENUM_END = 5;


} // namespace mace_mission
} // namespace mavlink

// MESSAGE DEFINITIONS
#include "./mavlink_msg_new_onboard_mission.hpp"
#include "./mavlink_msg_request_home_position.hpp"
#include "./mavlink_msg_home_position_ack.hpp"
#include "./mavlink_msg_guided_target_stats.hpp"

// base include

